name: Workflow 001 - Format

on:
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]
    paths:
      - "**.ts"
      - "**.tsx"
      - "**.json"

jobs:
  react-native-format:
    if: github.event.pull_request.draft == false || contains(github.event_name, 'workflow_dispatch')
    # Setup runner - `ubuntu-22.04` is as of 12/2023 the latest LTS ubuntu runner
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.8.1"

      - name: Install dependencies
        run: pnpm install

      - name: Run prettier format
        run: pnpm run prettier:check
