name: Workflow 002 - Lint

on:
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]
    paths:
      - "**.ts"
      - "**.tsx"
      - "**.js"
      - "**.jsx"

jobs:
  react-native-lint:
    if: github.event.pull_request.draft == false || contains(github.event_name, 'workflow_dispatch')

    # Setup runner - `ubuntu-22.04` is as of 12/2023 the latest LTS ubuntu runner
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.8.1"

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
            	args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, eslint, typescript]

      - name: Run ESlint format
        run: pnpm run eslint
